## Pytorch notes

In [8]:
import torch

### torch.tensor vs torch.Tensor:

I was referred to this [StackOverflow response](https://stackoverflow.com/questions/51911749/what-is-the-difference-between-torch-tensor-and-torch-tensor) as being one of the more helpful answers to this question.  

Of note, torch.tensor infers the dtype from the input data, whereas torch.Tensor returns Floats.

In [17]:
# Example:

## setup example data
words = ["emma"]
xs, xy = [], []

chars = sorted(list(set(''.join(words))))
chars.append(".")
stoi = {s:i + 1 for i, s in enumerate(chars)}

## create training data
for w in words:
    chs = ["."] + list(w) + ["."]
    for ch1, ch2, in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        xy.append(ix2)

xs = torch.Tensor(xs)
xy = torch.tensor(xy)


. e
e m
m m
m a
a .


In [18]:
xs

tensor([4., 2., 3., 3., 1.])

In [19]:
xy

tensor([2, 3, 3, 1, 4])

#### Testing inferences

In [20]:
b = [1, 2, 3, 4, 5, 6, 7, 8, 9]
c = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0,7.0, 8.0, 9.0]

b_t = torch.tensor(b)
c_t = torch.tensor(c)

bT = torch.Tensor(b)
cT = torch.Tensor(c)

In [21]:
b_t

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
bT

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
c_t

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
cT

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])